nohup python -u kals_model.py eva > nohup_eva.out &
nohup python -u kals_model.py sno > nohup_sno.out &
nohup python -u kals_model.py sub > nohup_sub.out &
nohup python -u kals_model.py sne > nohup_sne.out &
nohup python -u kals_model.py sue > nohup_sue.out &
nohup python -u kals_model.py sus > nohup_sus.out &
nohup python -u kals_model.py thr > nohup_thr.out &
nohup python -u kals_model.py xva > nohup_xva.out &
nohup python -u kals_model.py xno > nohup_xno.out &
nohup python -u kals_model.py xub > nohup_xub.out &
nohup python -u kals_model.py xne > nohup_xne.out &
nohup python -u kals_model.py xue > nohup_xue.out &
nohup python -u kals_model.py xus > nohup_xus.out &
nohup python -u kals_model.py xhr > nohup_xhr.out &
